# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://pandrews.github.io
title: Advice for New Students
email: pamela.andrews@tccd.edu
author: Pamela Andrews
description: Website project for 2019 Hacktoberfeset.  Current TCCD students provide advice that they wish they had known as first semester students. # "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
#copyright: 'Copyright &copy; 2019 Your Name. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  #- #title: twitter
    #url: https://twitter.com/plandrews14
  - title: github
    url: https://github.com/pandrews/advice
  #- title: linkedin
  #  url: 
